# Generated by Django 3.1.1 on 2020-09-29 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jimjam', '0003_superuser_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superuser',
            name='username',
        ),
    ]
